package com.example.android.mvvm.Model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

//Represents one note object and the table it represents in the Room database
//Entity is a Room annotation that creates the necessary SQLite code to create a table for the Note object on commpile time

@Entity(tableName = "note_table")
public class Note {
    //Member variables for the note
    //The primary key
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String title, description;
    private int priority;
    //id is autogenerated
    public Note(String title, String description, int priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
    }
    /*
    Since we don't include it in the constructor
    Room can access it thru this
    */
    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public int getPriority() {
        return priority;
    }
}
