package com.example.android.mvvm.Model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Calendar;
import java.util.Date;
//Represents one note object and the table it represents in the Room database
//Entity is a Room annotation that creates the necessary SQLite code to create a table for the Note object on commpile time
@Entity(tableName = "note_table")
public class Note {
    //Member variables for the note
    //The primary key
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String title, description;
    private Date reminderDate;
    private boolean reminderBoolean;
    private String category;

    //id is autogenerated
    public Note(String category, String title, String description, Date reminderDate, boolean reminderBoolean) {
        this.category = category;
        this.title = title;
        this.description = description;
        this.reminderDate = reminderDate;
        this.reminderBoolean = reminderBoolean;
    }

    /*
    Since we don't include it in the constructor
    Room can access it thru this
    */
    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public String getCategory() {
        return category;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public Date getReminderDate() {
        return reminderDate;
    }

    public boolean isReminderBoolean() {
        return reminderBoolean;
    }
}

